# Reload the required utterances list (since execution state was reset)
required_utterances = [
    "alright, have you played this game before?",
    "alright, so you're going to be the lava boy, down there. you're going to move with the arrow keys",
    "basically you can't touch what's opposite of you. so if you're fire, you can go into the fire, but you can't go into the water",
    "right there you can walk down",
    "and then this green, the green mud, is the, neither of us can touch it cause we",
    "if we, either of us touch it we both die",
    "so jump",
    "there you go",
    "yeah, these are the, these are the introductory levels",
    "alright, need you to push the button, so the",
    "so the ledge goes out, yeah",
    "stay on it",
    "and then let go",
    "then I'll touch it so you can get up",
    "come on down",
    "there you go. you've got the hang of it",
    "nah, nah, it's not mario",
    "yeah, I know. like in mario you normally go up",
    "right",
    "next level",
    "the same thing, same thing",
    "tada",
    "yeah",
    "the first",
    "yeah, oh yeah, there's green, yeah. but neither of us can touch the green",
    "yeah, you're good, you're good",
    "no",
    "sadly there isn't",
    "go for it",
    "but what if I'm, where is it, uh neither of us can land in, like, the opposite, but we can touch",
    "each other",
    "got caught, there you go",
    "there start again",
    "wonder if I can make it",
    "go for it",
    "you got this",
    "come on down",
    "that's it",
    "I think you have to like move out of the way, go out and come back in",
    "yeah, I'd like, I would get",
    "glitches a bit",
    "oh yeah, I was like, where'd you go",
    "going, I'm going, I'm going",
    "there you go",
    "renkei",
    "ooh",
    "okay, I think we have to",
    "do this",
    "there you are",
    "okay, there you go, so you can",
    "pull the lever",
    "yeah, I think that lever's going to pull something",
    "alright",
    "going",
    "that lever's going to, oh, okay, that lever lowers the thing so we can jump",
    "don't be greedy",
    "yeah, it's the green",
    "it",
    "ah oh okay",
    "yeah",
    "the green's the one getting you",
    "what happened?",
    "oh, I think you're",
    "yours got stuck",
    "there we go",
    "swing it",
    "stuck",
    "the gem, the gem, the gem. we want the points. we want them",
    "ah, okay, it's fine, it's fine, it's fine, we can still beat it",
    "see, now we got a b, cause we",
    "missed the gem",
    "left",
    "oh, it's like a little ladder, don't fall!",
    "yes, oh, okay, yeah you keep",
    "go",
    "ways",
    "okay I was, I was wondering, I was like are you heavier I, I did not expect that to happen okay",
    "oh, okay, so I guess we have to weigh each other down cause if not the other one falls down",
    "ah ah ah jump jump jump that, that was right, yeah",
    "yeah, that was my bad, I jumped too early",
    "okay, I think, yeah, you should go down first, like I said",
    "got it",
    "it's alright, okay, now it happened in reverse",
    "we should",
    "yeah, we'll both stay on it first",
    "like we could just keep hopping",
    "to keep moving around",
    "try to get you the like",
    "got to get",
    "bottom",
    "there we go",
    "be",
    "be greedy",
    "got you",
    "okay I got it",
    "okay okay okay we got it we got it we got it",
    "get",
    "oh no you have to hop, you have to go up",
    "why'd you fall, I I was concentrating on not you, not letting you fall. okay, we got close",
    "this again",
    "we're going to have to give each other, like, a little window to hop on that and hop back",
    "alright",
    "got it?",
    "up",
    "okay",
    "got it",
    "so",
    "and it's really, oh, okay",
    "oh yeah, cause then we both, like, yeah it's not going either way",
    "okay",
    "well, we, we'll try your idea",
    "go for it",
    "okay, how about, will we",
    "okay",
    "little",
    "down",
    "up",
    "it",
    "yeah I think it had, it had it was had like momentum",
    "going to",
    "have one, let's try one more time",
    "we won't be defeated",
    "yes",
    "yeah",
    "go",
    "so it's going down, jump",
    "yeah",
    "so you have to jump as it's going",
    "down",
    "wait",
    "it's",
    "level",
    "that one",
    "and then",
    "oh, okay",
    "ah, okay",
    "yeah, yeah let's just, let's just wait it out",
    "okay and then",
    "just fall into it, go",
    "there we go",
    "step",
    "step a little right, like, there you go we're good",
    "yeah, that",
    "yeah, that's good b, b team, we're good to go"
]

# Load the file content
input_file = "/mnt/data/transcription_with_refined_acts.txt"
with open(input_file, "r", encoding="utf-8") as f:
    lines = [line.strip().split("\t") for line in f]

# Create a dictionary for lookup
utterance_to_act = {parts[0]: parts[1] for parts in lines if len(parts) == 2}

# Corresponding filenames
filenames = [f"{i+1:03d}_{name}" for i, name in enumerate([
    "played_game", "lava_boy_arrow_keys", "cant_touch_opposite", "walk_down", "green_mud",
    "both_die", "jump", "there_you_go", "introductory_levels", "push_button", "ledge_goes_out",
    "stay_on_it", "let_go", "touch_to_get_up", "come_down", "got_the_hang", "not_mario", "mario_go_up",
    "right", "next_level", "same_thing", "tada", "yeah", "the_first", "neither_touch_green",
    "you_are_good", "no", "sadly_no", "go_for_it", "what_if", "each_other", "got_caught",
    "start_again", "wonder_if_make_it", "go_for_it", "you_got_this", "come_down", "thats_it",
    "move_out_way", "glitches", "where_you_go", "going_going", "there_you_go", "renkei", "ooh",
    "do_this", "there_you_are", "pull_lever", "lever_does_something", "alright", "going",
    "lever_lowers_jump", "dont_be_greedy", "green", "it", "ah_okay", "green_getting_you",
    "what_happened", "yours_stuck", "swing_it", "stuck", "gem_points", "its_fine", "missed_gem",
    "left", "dont_fall", "keep_going", "ways", "heavier_than_expected", "weigh_each_other",
    "jump_right", "jumped_too_early", "go_down_first", "got_it", "happened_reverse", "we_should",
    "stay_on_it", "keep_hopping", "keep_moving", "try_to_get", "got_to_get", "bottom", "be",
    "be_greedy", "got_you", "got_it", "we_got_it", "get"
])]

filtered_output = list(zip(filenames, required_utterances, [utterance_to_act[utt] for utt in required_utterances]))
filtered_output[:5]  # Preview first few results



# Attempt to write again using a different approach
try:
    with open('filtered_output.txt', "w", encoding="utf-8") as f:
        for name, text, act in filtered_output:
            f.write(f"('{name}', '{text}', '{act}')\n")
    success = True
except Exception as e:
    success = str(e)
